services:
  envp:
    build:
      context: .
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    image: envp:go-scratch
    ports:
      - "8080:8080"
    volumes:
      - envp-data:/data
    restart: unless-stopped

volumes:
  envp-data:
